### ISSUE TITLE
Sound Main Checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/sound-waves#1]
# {{SIM_NAME}} main checklist

## Design
- [ ] **Sim folder and design doc created** (Date: //)
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Review user feedback** 
   - [ ] *If a Port:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=677625918)
   - [ ] *If a new sim:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=898967246)
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //)
- [ ] **Mockups complete** (Date: //)
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion**
- [ ] **Interviews complete** (Date: //)
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //)
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-prototype items**
  - [ ] Auxiliary screenshots (at least 1 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL) as appropriate
  - [ ] Email/Twitter announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
- [ ] **Pre-publication items**
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Screen-specific screenshots for metadata service (see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Accessibility features
  - [ ] Email announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Make sim visible on website** 
   - [ ] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [ ] **Post-publication items**
  - [ ] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Email announcement
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Create "sim primer" issue
  - [ ] Hold postmortem if applicable (Date: //)

## Inclusive Features
- [ ] Alternative Input (Started: ) (Completed: ) 
- [ ] Pan & Zoom
- [ ] Sound & Sonification (UI)
- [ ] Sound & Sonification (Pedagogical) - (include link to relevant sonification design document)
    - [ ] Sound design complete (Started: ) (Completed: ) 
    - [ ] Development complete (Started: ) (Completed: ) 
- [ ] Interactive Description - (link to description design & implementation checklist)
    - [ ] Description design complete (Started: ) (Completed: ) 
    - [ ] Development complete (Started: ) (Completed: ) 
    - [ ] Mobile description included
- [ ] Voicing - (include links to relevant voicing design document)

## Implementation
- [ ] **Repository created** by following [new_repo_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/new_repo_checklist.md) (Date: //)
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //)
- [ ] **QA team "first look"** (Date: //)
- [ ] Interviews may happen around here (see above)
- [ ] **Code review checklist completed"** (Date: //)
- [ ] **Sim team sign-off** (Date: //)
- [ ] **Code review completed** (Date: //)
- [ ] **Sim dev test completed** (Date: //)
- [ ] **Sim RC tests completed** (Date: //)
- [ ] **Pre-publication items**
  - [ ] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#screenshots))
  - [ ] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks - see [conventions](https://github.com/phetsims/joist/blob/master/js/CreditsNode.js))
  - [ ] Add CT tests for public query parameters
- [ ] **Published** (Date: //)

## QA
- [ ] *If a Port:* **Legacy sim tested for bugs**; issues reported in repo
- [ ] **Dev testing started** (Date: //)
- [ ] **Dev testing completed** (Date: //)
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)
