### ISSUE TITLE
Checklist: Update Teaching Resources

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/sound-waves#21]
The teacher tips and metadata for the sim need to be updated before publishing as a prototype. I'd like to talk with @catherinecarter about what else to include in this checklist for the unique case of this sim.

**Comment by matthew-blackman** [comment]
Checklist for sim publication:
- [ ] Teacher tips
- [ ] Screenshots for website (see format below)
- [ ] Upload teacher tips and publish (with @catherinecarter )
- [ ] Save teacher tips to Sharepoint in the sim folder (as a Pages file and a pdf)
- [ ] Update keywords in PhET Basic Administration page (make sure in Sound HTML 5 after published)
- [ ] Ask KP where to acknowledge 3rd party devs (or POSE references)
- [ ] Check in with @catherinecarter to continue this list!

![Screen Shot 2023-08-16 at 1 40 26 PM](https://github.com/phetsims/sound/assets/108756567/7ad75a84-98f7-4c17-b419-63f8e3d6311d)
